bratmensclothing/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('',views.signup_user,name='signup_user'),
    path('loginuser/',views.login_user,name='login_user'),
    path('homeuser/',views.home_user,name='home_user'),    
    path('adminlogin/',views.admin_login,name='admin_login'),    
    path('adminlogout/',views.admin_logout,name='admin_logout'),  
    path('otp-verify/', views.otp_verify, name='otp_verify'),
    path('resend-otp/', views.resend_otp, name='resend_otp'),

]

bratmensclothing/bratmensclothing/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('products/',include('products.urls')),
    path('users/',include('users.urls')),
    path('dashboard/',include('dashboard.urls')),
]

bratmensclothing/users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'userss'

urlpatterns = [
    path('view_user/',views.view_user,name='view_user'),
    path('block-user/<int:user_id>',views.block_user,name='block_user'),
    path('unblock-user/<int:user_id>',views.unblock_user,name='unblock_user'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bratmensclothing/users/views.py
from django.shortcuts import render,redirect,get_object_or_404
from accounts.models import Users
from django.contrib import messages


def view_user(request):
    users=Users.objects.all()

    return render(request,'admin/users.html',{'users':users})


def block_user(request,user_id):
    users=get_object_or_404(Users,user_id=user_id)
    users.isBlocked=True
    users.save()
    messages.success(request,'User Blocked Succesfully')
    return redirect('userss:view_user')


def unblock_user(request,user_id):
    users=get_object_or_404(Users,user_id=user_id)
    users.isBlocked=False
    users.save()
    messages.success(request,'User Blocked Succesfully')
    return redirect('userss:view_user')

bratmensclothing/templates/user/login.html
{% extends "user/base.html" %}


{% block content %}
 
        
        <!--====== Section 1 ======-->
         <div class="">

            <!--====== Section Content ======-->
            <div class="section__content">
                <div class="container">
                    <div class="breadcrumb">
                        <div class="breadcrumb__wrap">
                            <ul class="breadcrumb__list">
                                <li class="has-separator">

                                    <a href="">Home</a></li>
                                <li class="is-marked">

                                    <a href="">login</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--====== End - Section 1 ======-->
   
<!--====== Section 2 ======-->
<div class="">

    <!--====== Section Intro ======-->
    <div class="section__intro u-s-p-b-40">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section__text-wrap">
                        <h2 class="section__heading u-c-secondary">ALREADY REGISTERED?</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--====== End - Section Intro ======-->


    <!--====== Section Content ======-->
    <div class="section__content">
        <div class="container">
            <div class="row row--center">
                <div class="col-lg-6 col-md-8 u-s-m-b-30">
                    <div class="l-f-o">
                        <div class="l-f-o__pad-box">
                            <h1 class="gl-h1">I'M NEW CUSTOMER</h1>

                            <span class="gl-text u-s-m-b-30">By creating an account with our store, you will be able to move through the checkout process faster, store shipping addresses, view and track your orders in your account and more.</span>
                            <div class="u-s-m-b-15">

                                <a class="l-f-o__create-link btn--e-transparent-brand-b-2" href="">CREATE AN ACCOUNT</a></div>
                            <h1 class="gl-h1">SIGNIN</h1>

                            <span class="gl-text u-s-m-b-30">If you have an account with us, please log in.</span>
                            <form class="l-f-o__form" method="post" id="loginForm" action="">
                                {% csrf_token %}
                                <div class="gl-s-api">
                                    <!-- <div class="u-s-m-b-15">

                                        <button class="gl-s-api__btn gl-s-api__btn--fb" type="button"><i class="fab fa-facebook-f"></i>

                                            <span>Signin with Facebook</span></button></div> -->
                                    <div class="u-s-m-b-15">

                                        <button class="gl-s-api__btn gl-s-api__btn--gplus" type="button"><i class="fab fa-google"></i>

                                            <span>Signin with Google</span></button></div>
                                </div>
                                <div class="u-s-m-b-30">

                                    <label class="gl-label" for="login-email">E-MAIL *</label>

                                    <input class="input-text input-text--primary-style" name="email" type="email" id="login-email" placeholder="Enter E-mail"></div>
                                <div class="u-s-m-b-30">

                                    <label class="gl-label" for="login-password">PASSWORD *</label>

                                    <input class="input-text input-text--primary-style" name="password" type="password" id="login-password" placeholder="Enter Password"></div>
                                <div class="gl-inline">
                                    <div class="u-s-m-b-30">

                                        <button class="btn btn--e-transparent-brand-b-2" type="submit">LOGIN</button></div>
                                    <div class="u-s-m-b-30">

                                        <a class="gl-link" href="">Lost Your Password?</a></div>
                                </div>
                                <div class="u-s-m-b-30">

                                    <!--====== Check Box ======-->
                                    <div class="check-box">

                                        <input type="checkbox" id="remember-me">
                                        <div class="check-box__state check-box__state--primary">

                                            <label class="check-box__label" for="remember-me">Remember Me</label></div>
                                    </div>
                                    <!--====== End - Check Box ======-->
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--====== End - Section Content ======-->
</div>
<!--====== End - Section 2 ======-->


{% endblock %}

bratmensclothing/templates/user/otp.html
{% extends "user/base.html" %}


{% block content %}


 <!--====== Section Content ======-->
 <div class="section__content">
    <div class="container">
        <div class="breadcrumb">
            <div class="breadcrumb__wrap">
                <ul class="breadcrumb__list">
                    <li class="has-separator">

                        <a href="">Home</a></li>
                    <li class="is-marked">

                        <a href="">Otp</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!--====== End - Section 1 ======-->
    
 <!--====== Section Intro ======-->
 <div class="section__intro u-s-m-b-60">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section__text-wrap">
                    <h6 class="section__heading u-c-secondary">VERIFY YOUR EMAIL ADDRESS</h6>
                </div>
            </div>
        </div>
    </div>
</div>
<!--====== End - Section Intro ======-->


<!--====== Section Content ======-->
<div class="section__content">
    <div class="container">
        <div class="row row--center">
            <div class="col-lg-6 col-md-8 u-s-m-b-30">
                <div class="l-f-o">
                    <div class="l-f-o__pad-box">

                        <span class="gl-text u-s-m-b-30 " style="color: black !important ;">We have sent otp to email, just use it here</span>
                        <div class="u-s-m-b-15">

                        <h1 class="gl-h1">Otp</h1>
                        <form class="l-f-o__form" method="post" id="loginForm" action="">
                            {% csrf_token %}
                            
                            <div class="u-s-m-b-30">

                                <label class="gl-label" for="login-password">OTP *</label>

                                <input class="input-text input-text--primary-style" name="otp" type="" id="login-Otp" placeholder="Enter Otp"></div>
                                {% if messages %}
                                <ul>
                                    {% for message in messages %}
                                        <li style="color: red;">{{ message }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                            
                                <div class="gl-inline">
                                <div class="u-s-m-b-30">

                                    <button class="btn btn--e-transparent-brand-b-2" type="submit">VERIFY</button></div>
                                <div class="u-s-m-b-30">

                                    <a class="gl-link" href="{% url 'accounts:resend_otp' %}">Resend Otp</a></div>
                            </div>
                            <div class="u-s-m-b-30">

                                <!--====== Check Box ======-->
                                <div class="u-s-m-b-30">

                                    <!-- <a class="gl-link" href="">You want to change your mail?  CLICK HERE</a></div> -->
                                <!--====== End - Check Box ======-->
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

bratmensclothing/templates/user/signup.html
{% extends "user/base.html" %}

{% block content %}


         <!--====== Section 1 ======-->
         <div class="">

            <!--====== Section Content ======-->
            <div class="section__content">
                <div class="container">
                    <div class="breadcrumb">
                        <div class="breadcrumb__wrap">
                            <ul class="breadcrumb__list">
                                <li class="has-separator">

                                    <a href="">Home</a></li>
                                <li class="is-marked">

                                    <a href="">Signup</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--====== End - Section 1 ======-->
   



    <!--====== Section 2 ======-->
    <div class="">

        <!--====== Section Intro ======-->
        <div class="section__intro u-s-p-b-40">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section__text-wrap">
                            <h2 class="section__heading u-c-secondary">CREATE AN ACCOUNT</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--====== End - Section Intro ======-->


        <!--====== Section Content ======-->

        <div class="section__content">
            <div class="container">
                <div class="row row--center">
                    <div class="col-lg-6 col-md-8 u-s-m-b-30">
                        <div class="l-f-o">
                            <div class="l-f-o__pad-box">
                                <h1 class="gl-h1">PERSONAL INFORMATION</h1>
                                <form class="l-f-o__form" method="post" action="" id="signupForm">
                                    {% csrf_token %}
                                    <div class="gl-s-api">
                                        <!-- <div class="u-s-m-b-15">

                                            <button class="gl-s-api__btn gl-s-api__btn--fb" type="button"><i class="fab fa-facebook-f"></i>

                                                <span>Signup with Facebook</span></button></div> -->
                                        <div class="u-s-m-b-30">

                                            <button class="gl-s-api__btn gl-s-api__btn--gplus" type="button"><i class="fab fa-google"></i>

                                                <span>Signup with Google</span></button></div>
                                    </div>

                                    <div id="responseMessage"></div>

                                    <div class="u-s-m-b-30">

                                        <label class="gl-label" for="reg-fname">NAME *</label>

                                        <input class="input-text input-text--primary-style" type="text" required name="username" id="reg-fname" placeholder="First Name"></div>
                                    <div class="u-s-m-b-30">

                                        <label class="gl-label" for="reg-phone">PHONE </label>

                                        <input class="input-text input-text--primary-style" type="" required name="phone" id="reg-phone" placeholder="Enter phone Number"></div>
                                
                                    <div class="u-s-m-b-30">

                                        <label class="gl-label" for="reg-email">E-MAIL *</label>

                                        <input class="input-text input-text--primary-style" type="email" required name="email" id="reg-email" placeholder="Enter E-mail"></div>
                                    <div class="u-s-m-b-30">

                                        <label class="gl-label" for="reg-password">PASSWORD *</label>

                                        <input class="input-text input-text--primary-style" type="password" required name="password1" id="reg-password" placeholder="Enter Password"></div>
    
                                    <div class="u-s-m-b-30">

                                        <label class="gl-label" for="reg-password">RE-ENTER PASSWORD *</label>

                                        <input class="input-text input-text--primary-style" type="password" required name="password2" id="reg-password" placeholder="Re-Enter Password"></div>
                                
                                    <div class="u-s-m-b-15">
                                        
                                    <a href="{% url 'accounts:otp_verify' %}" class="btn btn--e-transparent-brand-b-2">CREATE</a>

                                    <button class="btn btn--e-transparent-brand-b-2" type="submit">CREATE</button></div>

                                    <a class="gl-link" href="#">Return to Store</a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!--====== End - Section Content ======-->
    </div>
    <!--====== End - Section 2 ======-->   


    {% endblock %}